---
name: Repo

on:
  push:
    branches:
      - "main"

jobs:
  test-image:
    name: Create badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install python dependencies
        run: pip install ".[ci]" 

      - name: Run tests with coverage
        run: hatch run test:cov

      - name: Create coverage badge
        run: genbadge coverage -i .coverage.xml

      - name: Create test badge
        run: genbadge tests -i .junit.xml

      - name: Upload coverage badge
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: e60a9d0af9c141f6d2a3e0bd09366f5f
          file_path: coverage-badge.svg

      - name: Upload tests badge
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 79f221f23ccd460bba50b81f0df78ae1
          file_path: tests-badge.svg
